// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.12.4
// source: src/contracts/feed-content/feed.content.query.proto

package feed_service

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// an enumeration about the different kind of media items the service supports
type MediaItemKind int32

const (
	MediaItemKind_KIND_UNSPECIFIED MediaItemKind = 0
	MediaItemKind_KIND_IMAGES      MediaItemKind = 1
	MediaItemKind_KIND_VIDEO       MediaItemKind = 2
)

// Enum value maps for MediaItemKind.
var (
	MediaItemKind_name = map[int32]string{
		0: "KIND_UNSPECIFIED",
		1: "KIND_IMAGES",
		2: "KIND_VIDEO",
	}
	MediaItemKind_value = map[string]int32{
		"KIND_UNSPECIFIED": 0,
		"KIND_IMAGES":      1,
		"KIND_VIDEO":       2,
	}
)

func (x MediaItemKind) Enum() *MediaItemKind {
	p := new(MediaItemKind)
	*p = x
	return p
}

func (x MediaItemKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MediaItemKind) Descriptor() protoreflect.EnumDescriptor {
	return file_src_contracts_feed_content_feed_content_query_proto_enumTypes[0].Descriptor()
}

func (MediaItemKind) Type() protoreflect.EnumType {
	return &file_src_contracts_feed_content_feed_content_query_proto_enumTypes[0]
}

func (x MediaItemKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MediaItemKind.Descriptor instead.
func (MediaItemKind) EnumDescriptor() ([]byte, []int) {
	return file_src_contracts_feed_content_feed_content_query_proto_rawDescGZIP(), []int{0}
}

type ItemVisibility int32

const (
	ItemVisibility_VISIBILITY_UNSPECIFIED ItemVisibility = 0
	ItemVisibility_VISIBILITY_PRIVATE     ItemVisibility = 1
	ItemVisibility_VISIBILITY_PUBLIC      ItemVisibility = 2
)

// Enum value maps for ItemVisibility.
var (
	ItemVisibility_name = map[int32]string{
		0: "VISIBILITY_UNSPECIFIED",
		1: "VISIBILITY_PRIVATE",
		2: "VISIBILITY_PUBLIC",
	}
	ItemVisibility_value = map[string]int32{
		"VISIBILITY_UNSPECIFIED": 0,
		"VISIBILITY_PRIVATE":     1,
		"VISIBILITY_PUBLIC":      2,
	}
)

func (x ItemVisibility) Enum() *ItemVisibility {
	p := new(ItemVisibility)
	*p = x
	return p
}

func (x ItemVisibility) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ItemVisibility) Descriptor() protoreflect.EnumDescriptor {
	return file_src_contracts_feed_content_feed_content_query_proto_enumTypes[1].Descriptor()
}

func (ItemVisibility) Type() protoreflect.EnumType {
	return &file_src_contracts_feed_content_feed_content_query_proto_enumTypes[1]
}

func (x ItemVisibility) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ItemVisibility.Descriptor instead.
func (ItemVisibility) EnumDescriptor() ([]byte, []int) {
	return file_src_contracts_feed_content_feed_content_query_proto_rawDescGZIP(), []int{1}
}

// an enumeration about the different kind of notifications supported
type NotificationKind int32

const (
	NotificationKind_KIND_COMMENT  NotificationKind = 0
	NotificationKind_KIND_FOLLOWER NotificationKind = 1
	NotificationKind_KIND_LIKE     NotificationKind = 2
)

// Enum value maps for NotificationKind.
var (
	NotificationKind_name = map[int32]string{
		0: "KIND_COMMENT",
		1: "KIND_FOLLOWER",
		2: "KIND_LIKE",
	}
	NotificationKind_value = map[string]int32{
		"KIND_COMMENT":  0,
		"KIND_FOLLOWER": 1,
		"KIND_LIKE":     2,
	}
)

func (x NotificationKind) Enum() *NotificationKind {
	p := new(NotificationKind)
	*p = x
	return p
}

func (x NotificationKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotificationKind) Descriptor() protoreflect.EnumDescriptor {
	return file_src_contracts_feed_content_feed_content_query_proto_enumTypes[2].Descriptor()
}

func (NotificationKind) Type() protoreflect.EnumType {
	return &file_src_contracts_feed_content_feed_content_query_proto_enumTypes[2]
}

func (x NotificationKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotificationKind.Descriptor instead.
func (NotificationKind) EnumDescriptor() ([]byte, []int) {
	return file_src_contracts_feed_content_feed_content_query_proto_rawDescGZIP(), []int{2}
}

type FeedContentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tags   []string `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	UserId string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Paging *Paging  `protobuf:"bytes,3,opt,name=paging,proto3" json:"paging,omitempty"`
}

func (x *FeedContentRequest) Reset() {
	*x = FeedContentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_contracts_feed_content_feed_content_query_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FeedContentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedContentRequest) ProtoMessage() {}

func (x *FeedContentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_contracts_feed_content_feed_content_query_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedContentRequest.ProtoReflect.Descriptor instead.
func (*FeedContentRequest) Descriptor() ([]byte, []int) {
	return file_src_contracts_feed_content_feed_content_query_proto_rawDescGZIP(), []int{0}
}

func (x *FeedContentRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *FeedContentRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *FeedContentRequest) GetPaging() *Paging {
	if x != nil {
		return x.Paging
	}
	return nil
}

type FeedContentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MediaItems    []*MediaItem    `protobuf:"bytes,1,rep,name=media_items,json=mediaItems,proto3" json:"media_items,omitempty"`
	Notifications []*Notification `protobuf:"bytes,2,rep,name=notifications,proto3" json:"notifications,omitempty"`
}

func (x *FeedContentResponse) Reset() {
	*x = FeedContentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_contracts_feed_content_feed_content_query_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FeedContentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedContentResponse) ProtoMessage() {}

func (x *FeedContentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_contracts_feed_content_feed_content_query_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedContentResponse.ProtoReflect.Descriptor instead.
func (*FeedContentResponse) Descriptor() ([]byte, []int) {
	return file_src_contracts_feed_content_feed_content_query_proto_rawDescGZIP(), []int{1}
}

func (x *FeedContentResponse) GetMediaItems() []*MediaItem {
	if x != nil {
		return x.MediaItems
	}
	return nil
}

func (x *FeedContentResponse) GetNotifications() []*Notification {
	if x != nil {
		return x.Notifications
	}
	return nil
}

type Paging struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Anchor *string `protobuf:"bytes,1,opt,name=anchor,proto3,oneof" json:"anchor,omitempty"`
	Limit  *uint32 `protobuf:"varint,2,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
}

func (x *Paging) Reset() {
	*x = Paging{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_contracts_feed_content_feed_content_query_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Paging) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Paging) ProtoMessage() {}

func (x *Paging) ProtoReflect() protoreflect.Message {
	mi := &file_src_contracts_feed_content_feed_content_query_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Paging.ProtoReflect.Descriptor instead.
func (*Paging) Descriptor() ([]byte, []int) {
	return file_src_contracts_feed_content_feed_content_query_proto_rawDescGZIP(), []int{2}
}

func (x *Paging) GetAnchor() string {
	if x != nil && x.Anchor != nil {
		return *x.Anchor
	}
	return ""
}

func (x *Paging) GetLimit() uint32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

type MediaItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// the unique identifier of the media item
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// the url to access the concrete media on content storage directly - this is usually a temporary link
	Url string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	// the kind of item
	Kind MediaItemKind `protobuf:"varint,3,opt,name=kind,proto3,enum=contracts.feed_content.MediaItemKind" json:"kind,omitempty"`
	// the content type of the media
	ContentType string `protobuf:"bytes,4,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	// the description set by the user while upload
	Description string `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	// a list of tags for the given media
	Tags []string `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	// the user id of the owner
	OwnerId string `protobuf:"bytes,7,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	// the thumbnail url
	ThumbnailUrl string `protobuf:"bytes,8,opt,name=thumbnail_url,json=thumbnailUrl,proto3" json:"thumbnail_url,omitempty"`
	// the timestamp the media was created
	UploadedAt *timestamp.Timestamp `protobuf:"bytes,9,opt,name=uploaded_at,json=uploadedAt,proto3,oneof" json:"uploaded_at,omitempty"`
	// the timestamp the media was modified
	LastModifiedAt *timestamp.Timestamp `protobuf:"bytes,10,opt,name=last_modified_at,json=lastModifiedAt,proto3,oneof" json:"last_modified_at,omitempty"`
	// the visibility of the media item
	Visibility ItemVisibility `protobuf:"varint,11,opt,name=visibility,proto3,enum=contracts.feed_content.ItemVisibility" json:"visibility,omitempty"`
	// the version of the media item
	Version uint64 `protobuf:"varint,12,opt,name=Version,proto3" json:"Version,omitempty"`
}

func (x *MediaItem) Reset() {
	*x = MediaItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_contracts_feed_content_feed_content_query_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MediaItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaItem) ProtoMessage() {}

func (x *MediaItem) ProtoReflect() protoreflect.Message {
	mi := &file_src_contracts_feed_content_feed_content_query_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaItem.ProtoReflect.Descriptor instead.
func (*MediaItem) Descriptor() ([]byte, []int) {
	return file_src_contracts_feed_content_feed_content_query_proto_rawDescGZIP(), []int{3}
}

func (x *MediaItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MediaItem) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *MediaItem) GetKind() MediaItemKind {
	if x != nil {
		return x.Kind
	}
	return MediaItemKind_KIND_UNSPECIFIED
}

func (x *MediaItem) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *MediaItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MediaItem) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *MediaItem) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *MediaItem) GetThumbnailUrl() string {
	if x != nil {
		return x.ThumbnailUrl
	}
	return ""
}

func (x *MediaItem) GetUploadedAt() *timestamp.Timestamp {
	if x != nil {
		return x.UploadedAt
	}
	return nil
}

func (x *MediaItem) GetLastModifiedAt() *timestamp.Timestamp {
	if x != nil {
		return x.LastModifiedAt
	}
	return nil
}

func (x *MediaItem) GetVisibility() ItemVisibility {
	if x != nil {
		return x.Visibility
	}
	return ItemVisibility_VISIBILITY_UNSPECIFIED
}

func (x *MediaItem) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId    string               `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Timestamp *timestamp.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *Data) Reset() {
	*x = Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_contracts_feed_content_feed_content_query_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_src_contracts_feed_content_feed_content_query_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_src_contracts_feed_content_feed_content_query_proto_rawDescGZIP(), []int{4}
}

func (x *Data) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Data) GetTimestamp() *timestamp.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type Notification struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind NotificationKind `protobuf:"varint,1,opt,name=kind,proto3,enum=contracts.feed_content.NotificationKind" json:"kind,omitempty"`
	Data *Data            `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Notification) Reset() {
	*x = Notification{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_contracts_feed_content_feed_content_query_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notification) ProtoMessage() {}

func (x *Notification) ProtoReflect() protoreflect.Message {
	mi := &file_src_contracts_feed_content_feed_content_query_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notification.ProtoReflect.Descriptor instead.
func (*Notification) Descriptor() ([]byte, []int) {
	return file_src_contracts_feed_content_feed_content_query_proto_rawDescGZIP(), []int{5}
}

func (x *Notification) GetKind() NotificationKind {
	if x != nil {
		return x.Kind
	}
	return NotificationKind_KIND_COMMENT
}

func (x *Notification) GetData() *Data {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_src_contracts_feed_content_feed_content_query_proto protoreflect.FileDescriptor

var file_src_contracts_feed_content_feed_content_query_proto_rawDesc = []byte{
	0x0a, 0x33, 0x73, 0x72, 0x63, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x73, 0x2f,
	0x66, 0x65, 0x65, 0x64, 0x2d, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x2f, 0x66, 0x65, 0x65,
	0x64, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x2e, 0x71, 0x75, 0x65, 0x72, 0x79, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x16, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x73,
	0x2e, 0x66, 0x65, 0x65, 0x64, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x1a, 0x1f, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x79,
	0x0a, 0x12, 0x46, 0x65, 0x65, 0x64, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x04, 0x74, 0x61, 0x67, 0x73, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x36, 0x0a, 0x06, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1e, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x73, 0x2e, 0x66, 0x65,
	0x65, 0x64, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x2e, 0x50, 0x61, 0x67, 0x69, 0x6e,
	0x67, 0x52, 0x06, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x22, 0xa5, 0x01, 0x0a, 0x13, 0x46, 0x65,
	0x65, 0x64, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x42, 0x0a, 0x0b, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x5f, 0x69, 0x74, 0x65, 0x6d, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63,
	0x74, 0x73, 0x2e, 0x66, 0x65, 0x65, 0x64, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x2e,
	0x4d, 0x65, 0x64, 0x69, 0x61, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x0a, 0x6d, 0x65, 0x64, 0x69, 0x61,
	0x49, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x4a, 0x0a, 0x0d, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x63,
	0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x73, 0x2e, 0x66, 0x65, 0x65, 0x64, 0x5f, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x2e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x0d, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x22, 0x55, 0x0a, 0x06, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x12, 0x1b, 0x0a, 0x06, 0x61,
	0x6e, 0x63, 0x68, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x06, 0x61,
	0x6e, 0x63, 0x68, 0x6f, 0x72, 0x88, 0x01, 0x01, 0x12, 0x19, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x01, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74,
	0x88, 0x01, 0x01, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x61, 0x6e, 0x63, 0x68, 0x6f, 0x72, 0x42, 0x08,
	0x0a, 0x06, 0x5f, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x95, 0x04, 0x0a, 0x09, 0x4d, 0x65, 0x64,
	0x69, 0x61, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x39, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x25, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63,
	0x74, 0x73, 0x2e, 0x66, 0x65, 0x65, 0x64, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x2e,
	0x4d, 0x65, 0x64, 0x69, 0x61, 0x49, 0x74, 0x65, 0x6d, 0x4b, 0x69, 0x6e, 0x64, 0x52, 0x04, 0x6b,
	0x69, 0x6e, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x5f, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x73,
	0x18, 0x06, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x74, 0x61, 0x67, 0x73, 0x12, 0x19, 0x0a, 0x08,
	0x6f, 0x77, 0x6e, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6f, 0x77, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x74, 0x68, 0x75, 0x6d, 0x62,
	0x6e, 0x61, 0x69, 0x6c, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x74, 0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61, 0x69, 0x6c, 0x55, 0x72, 0x6c, 0x12, 0x40, 0x0a, 0x0b,
	0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x48, 0x00, 0x52,
	0x0a, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x64, 0x41, 0x74, 0x88, 0x01, 0x01, 0x12, 0x49,
	0x0a, 0x10, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x6d, 0x6f, 0x64, 0x69, 0x66, 0x69, 0x65, 0x64, 0x5f,
	0x61, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x48, 0x01, 0x52, 0x0e, 0x6c, 0x61, 0x73, 0x74, 0x4d, 0x6f, 0x64, 0x69,
	0x66, 0x69, 0x65, 0x64, 0x41, 0x74, 0x88, 0x01, 0x01, 0x12, 0x46, 0x0a, 0x0a, 0x76, 0x69, 0x73,
	0x69, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x26, 0x2e,
	0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x73, 0x2e, 0x66, 0x65, 0x65, 0x64, 0x5f, 0x63,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x56, 0x69, 0x73, 0x69, 0x62,
	0x69, 0x6c, 0x69, 0x74, 0x79, 0x52, 0x0a, 0x76, 0x69, 0x73, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x74,
	0x79, 0x12, 0x18, 0x0a, 0x07, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x0c, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x07, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x42, 0x0e, 0x0a, 0x0c, 0x5f,
	0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x42, 0x13, 0x0a, 0x11, 0x5f,
	0x6c, 0x61, 0x73, 0x74, 0x5f, 0x6d, 0x6f, 0x64, 0x69, 0x66, 0x69, 0x65, 0x64, 0x5f, 0x61, 0x74,
	0x22, 0x59, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x38, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x7e, 0x0a, 0x0c, 0x4e,
	0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x3c, 0x0a, 0x04, 0x6b,
	0x69, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x28, 0x2e, 0x63, 0x6f, 0x6e, 0x74,
	0x72, 0x61, 0x63, 0x74, 0x73, 0x2e, 0x66, 0x65, 0x65, 0x64, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x2e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4b,
	0x69, 0x6e, 0x64, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12, 0x30, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61,
	0x63, 0x74, 0x73, 0x2e, 0x66, 0x65, 0x65, 0x64, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x2a, 0x46, 0x0a, 0x0d, 0x4d,
	0x65, 0x64, 0x69, 0x61, 0x49, 0x74, 0x65, 0x6d, 0x4b, 0x69, 0x6e, 0x64, 0x12, 0x14, 0x0a, 0x10,
	0x4b, 0x49, 0x4e, 0x44, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44,
	0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x4b, 0x49, 0x4e, 0x44, 0x5f, 0x49, 0x4d, 0x41, 0x47, 0x45,
	0x53, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x4b, 0x49, 0x4e, 0x44, 0x5f, 0x56, 0x49, 0x44, 0x45,
	0x4f, 0x10, 0x02, 0x2a, 0x5b, 0x0a, 0x0e, 0x49, 0x74, 0x65, 0x6d, 0x56, 0x69, 0x73, 0x69, 0x62,
	0x69, 0x6c, 0x69, 0x74, 0x79, 0x12, 0x1a, 0x0a, 0x16, 0x56, 0x49, 0x53, 0x49, 0x42, 0x49, 0x4c,
	0x49, 0x54, 0x59, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10,
	0x00, 0x12, 0x16, 0x0a, 0x12, 0x56, 0x49, 0x53, 0x49, 0x42, 0x49, 0x4c, 0x49, 0x54, 0x59, 0x5f,
	0x50, 0x52, 0x49, 0x56, 0x41, 0x54, 0x45, 0x10, 0x01, 0x12, 0x15, 0x0a, 0x11, 0x56, 0x49, 0x53,
	0x49, 0x42, 0x49, 0x4c, 0x49, 0x54, 0x59, 0x5f, 0x50, 0x55, 0x42, 0x4c, 0x49, 0x43, 0x10, 0x02,
	0x2a, 0x46, 0x0a, 0x10, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x4b, 0x69, 0x6e, 0x64, 0x12, 0x10, 0x0a, 0x0c, 0x4b, 0x49, 0x4e, 0x44, 0x5f, 0x43, 0x4f, 0x4d,
	0x4d, 0x45, 0x4e, 0x54, 0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d, 0x4b, 0x49, 0x4e, 0x44, 0x5f, 0x46,
	0x4f, 0x4c, 0x4c, 0x4f, 0x57, 0x45, 0x52, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x4b, 0x49, 0x4e,
	0x44, 0x5f, 0x4c, 0x49, 0x4b, 0x45, 0x10, 0x02, 0x32, 0x70, 0x0a, 0x0b, 0x46, 0x65, 0x65, 0x64,
	0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x61, 0x0a, 0x04, 0x46, 0x65, 0x65, 0x64, 0x12,
	0x2a, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x73, 0x2e, 0x66, 0x65, 0x65, 0x64,
	0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x2e, 0x46, 0x65, 0x65, 0x64, 0x43, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2b, 0x2e, 0x63, 0x6f,
	0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x73, 0x2e, 0x66, 0x65, 0x65, 0x64, 0x5f, 0x63, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x2e, 0x46, 0x65, 0x65, 0x64, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x16, 0x5a, 0x14, 0x63, 0x69,
	0x64, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x66, 0x65, 0x65, 0x64, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_src_contracts_feed_content_feed_content_query_proto_rawDescOnce sync.Once
	file_src_contracts_feed_content_feed_content_query_proto_rawDescData = file_src_contracts_feed_content_feed_content_query_proto_rawDesc
)

func file_src_contracts_feed_content_feed_content_query_proto_rawDescGZIP() []byte {
	file_src_contracts_feed_content_feed_content_query_proto_rawDescOnce.Do(func() {
		file_src_contracts_feed_content_feed_content_query_proto_rawDescData = protoimpl.X.CompressGZIP(file_src_contracts_feed_content_feed_content_query_proto_rawDescData)
	})
	return file_src_contracts_feed_content_feed_content_query_proto_rawDescData
}

var file_src_contracts_feed_content_feed_content_query_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_src_contracts_feed_content_feed_content_query_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_src_contracts_feed_content_feed_content_query_proto_goTypes = []interface{}{
	(MediaItemKind)(0),          // 0: contracts.feed_content.MediaItemKind
	(ItemVisibility)(0),         // 1: contracts.feed_content.ItemVisibility
	(NotificationKind)(0),       // 2: contracts.feed_content.NotificationKind
	(*FeedContentRequest)(nil),  // 3: contracts.feed_content.FeedContentRequest
	(*FeedContentResponse)(nil), // 4: contracts.feed_content.FeedContentResponse
	(*Paging)(nil),              // 5: contracts.feed_content.Paging
	(*MediaItem)(nil),           // 6: contracts.feed_content.MediaItem
	(*Data)(nil),                // 7: contracts.feed_content.Data
	(*Notification)(nil),        // 8: contracts.feed_content.Notification
	(*timestamp.Timestamp)(nil), // 9: google.protobuf.Timestamp
}
var file_src_contracts_feed_content_feed_content_query_proto_depIdxs = []int32{
	5,  // 0: contracts.feed_content.FeedContentRequest.paging:type_name -> contracts.feed_content.Paging
	6,  // 1: contracts.feed_content.FeedContentResponse.media_items:type_name -> contracts.feed_content.MediaItem
	8,  // 2: contracts.feed_content.FeedContentResponse.notifications:type_name -> contracts.feed_content.Notification
	0,  // 3: contracts.feed_content.MediaItem.kind:type_name -> contracts.feed_content.MediaItemKind
	9,  // 4: contracts.feed_content.MediaItem.uploaded_at:type_name -> google.protobuf.Timestamp
	9,  // 5: contracts.feed_content.MediaItem.last_modified_at:type_name -> google.protobuf.Timestamp
	1,  // 6: contracts.feed_content.MediaItem.visibility:type_name -> contracts.feed_content.ItemVisibility
	9,  // 7: contracts.feed_content.Data.timestamp:type_name -> google.protobuf.Timestamp
	2,  // 8: contracts.feed_content.Notification.kind:type_name -> contracts.feed_content.NotificationKind
	7,  // 9: contracts.feed_content.Notification.data:type_name -> contracts.feed_content.Data
	3,  // 10: contracts.feed_content.FeedContent.Feed:input_type -> contracts.feed_content.FeedContentRequest
	4,  // 11: contracts.feed_content.FeedContent.Feed:output_type -> contracts.feed_content.FeedContentResponse
	11, // [11:12] is the sub-list for method output_type
	10, // [10:11] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_src_contracts_feed_content_feed_content_query_proto_init() }
func file_src_contracts_feed_content_feed_content_query_proto_init() {
	if File_src_contracts_feed_content_feed_content_query_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_src_contracts_feed_content_feed_content_query_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FeedContentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_contracts_feed_content_feed_content_query_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FeedContentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_contracts_feed_content_feed_content_query_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Paging); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_contracts_feed_content_feed_content_query_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MediaItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_contracts_feed_content_feed_content_query_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_contracts_feed_content_feed_content_query_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Notification); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_src_contracts_feed_content_feed_content_query_proto_msgTypes[2].OneofWrappers = []interface{}{}
	file_src_contracts_feed_content_feed_content_query_proto_msgTypes[3].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_src_contracts_feed_content_feed_content_query_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_src_contracts_feed_content_feed_content_query_proto_goTypes,
		DependencyIndexes: file_src_contracts_feed_content_feed_content_query_proto_depIdxs,
		EnumInfos:         file_src_contracts_feed_content_feed_content_query_proto_enumTypes,
		MessageInfos:      file_src_contracts_feed_content_feed_content_query_proto_msgTypes,
	}.Build()
	File_src_contracts_feed_content_feed_content_query_proto = out.File
	file_src_contracts_feed_content_feed_content_query_proto_rawDesc = nil
	file_src_contracts_feed_content_feed_content_query_proto_goTypes = nil
	file_src_contracts_feed_content_feed_content_query_proto_depIdxs = nil
}
